W10D4/solution/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create]
  resources :comments, only: [:create, :show] do
    member do
      post 'downvote'
      post 'upvote'
    end
  end
  resources :subs, except: [:destroy]
  resources :posts, except: [:destroy, :index] do
    resources :comments, only: [:new]
    member do
      post 'downvote'
      post 'upvote'
    end
  end

  root to: redirect('/subs')
end

W10D4/solution/app/models/comment.rb
class Comment < ApplicationRecord
  include Votable

  validates :body, presence: true

  after_initialize :ensure_post_id!

  belongs_to :post, inverse_of: :comments

  belongs_to :author,
    class_name: :User,
    foreign_key: :user_id,
    inverse_of: :comments

  has_many :child_comments,
    class_name: :Comment,
    foreign_key: :parent_comment_id,
    primary_key: :id

  belongs_to :parent_comment,
    class_name: :Comment,
    foreign_key: :parent_comment_id,
    primary_key: :id,
    optional: true

  private
  def ensure_post_id!
    self.post_id ||= self.parent_comment.post_id if parent_comment
  end
end

W10D4/solution/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_signed_in!, only: [:new, :create]

  def new
    @comment = Comment.new(post_id: params[:post_id])
  end

  def create
    @comment = current_user.comments.new(comment_params)

    if @comment.save!
      redirect_to post_url(@comment.post_id)
    else
      flash[:errors] = @comment.errors.full_messages
      redirect_to new_post_comment_url(@comment.post_id)
    end
  end

  def show
    @comment = Comment.find(params[:id])
    @new_comment = @comment.child_comments.new
  end

  def downvote
    vote(-1)
  end

  def upvote
    vote(1)
  end

  private
  def comment_params
    params.require(:comment).permit(:body, :post_id, :parent_comment_id)
  end

  def vote(direction)
    @comment = Comment.find(params[:id])
    @user_vote = @comment.user_votes.find_or_initialize_by(user: current_user)

    unless @user_vote.update(value: direction)
      flash[:errors] = @user_vote.errors.full_messages
    end

    redirect_to comment_url(@comment)
  end
end

W10D4/solution/app/helpers/comments_helper.rb
module CommentsHelper
end

W10D4/solution/app/views/comments/_comment.html.erb
<p>
  (<%= comment.votes %>) <a href="<%= comment_url(comment.id) %>"><%= comment.body %></a>
</p>

<ul>
  <% comments_by_parent[comment.id].each do |child_comment| %>
    <li><%= render("comments/comment",
            comment: child_comment,
            comments_by_parent: comments_by_parent) %></li>
  <% end %>
</ul>

W10D4/solution/app/views/comments/_form.html.erb
<form action="<%= comments_url %>" method="POST">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <input
    type="hidden"
    name="comment[post_id]"
    value="<%= comment.post_id %>">
  <input
    type="hidden"
    name="comment[parent_comment_id]"
    value="<%= comment.parent_comment_id %>">

  <label>
    Body
    <br>
    <textarea name="comment[body]"><%= comment.body %></textarea>
  </label>
  <br>

  <input type="submit">
</form>

W10D4/solution/app/views/comments/new.html.erb
<div class="border">
  <h1>New Comment!</h1>

  <%= render "form", comment: @comment %>
</div>

W10D4/solution/app/views/comments/show.html.erb
<div class="border"
  <%= @comment.body %> by <%= @comment.author.name %><br>
  <%= @comment.votes %> upvotes
  <br><br>

  <form action="<%= upvote_comment_url(@comment) %>" method="post">
    <input
      type="hidden"
      name="authenticity_token"
      value="<%= form_authenticity_token %>">
    <input type="submit" value="Upvote">
  </form>
  <form action="<%= downvote_comment_url(@comment) %>" method="post">
    <input
      type="hidden"
      name="authenticity_token"
      value="<%= form_authenticity_token %>">
    <input type="submit" value="Downvote">
  </form>

  <b>Reply to this comment:</b>
  <%= render "form", comment: @new_comment %>
</div>