W9D4/ben_ellis_skeleton/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats, except: :destroy
  resources :cat_rental_requests, only: [:new, :create] do
    member do
      post :approve
      post :deny
    end
  end

  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]

  root to: redirect('/cats')
end

W9D4/ben_ellis_skeleton/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  username        :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
require 'bcrypt'
require 'byebug'

class User < ApplicationRecord
  include BCrypt
  validates :username, :password_digest, :session_token, presence: true
  validates :username, :session_token, uniqueness: true
  attr_reader :password

  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def self.find_by_credentials(user_name, password)
    user = User.find_by(username: user_name)
    return nil unless user && user.is_password?(password)
    user 
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save!
  end

  def password=(new_pass)
    @password_digest = Password.create(new_pass)
    self.password_digest = @password_digest
  end

  def is_password?(pass)
    bcrypt_pass = Password.new(self.password_digest)
    bcrypt_pass.is_password?(pass)
  end

end

W9D4/ben_ellis_skeleton/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    render :show
  end


  def new 
    @user = User.new
    render :new 
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  private 

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

W9D4/ben_ellis_skeleton/app/views/users/new.html.erb
<% #action = (user.persisted? ? user_url(user) : users_url) %>
<% #method = (.persisted? ? :patch : :post) %>
<%= render 'shared/errors' %>

<form action="<%= users_url %>" method="post">
  <label for="username">Name</label>
  <input
    type="text"
    name="user[username]"
    id="username"
    value="<%= @user.username %>">

  <label for="user_password">Password</label>
  <input
    type="password"
    name="user[password]"
    id="user_password"
    value="<%= @user.password %>">
  <br>

  <input type="submit">
</form>

W9D4/ben_ellis_skeleton/app/views/users/show.html.erb
<h1><%= @user.username %></h1>